service: leakd-email-lambda

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  memorySize: 500
  timeout: 10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject*
        - s3:List*
      Resource: arn:aws:s3:::${param:dataBucketName}/*
    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource: "*"

  environment:
    SES_EMAIL_SENDER: noresponse@leakd.in
    SES_EMAIL_RECIPIENT: jacobgrimm@ymail.com

functions:
  new_file_processing_email:
    handler: src/lambda.handler
    events:
      - s3:
          bucket: ${param:dataBucketName}
          event: s3:ObjectCreated:*
          rules:
            - prefix: items/
          existing: true
resources:
  Resources:
    SESSenderIdentity:
      Type: AWS::SES::EmailIdentity
      Properties:
        EmailIdentity: noresponse@leakd.in
