service: Pwnd-S3-Bucket-Creator
### this serverless template just serves to create our 3 buckets used throughout the service
### One is the rawData bucket, in which admin's of the service can load raw credential files into the bucket to trigger a processing lambda
### One is the codeBucket, which we use to store our EC2 instance's code
### Final one is our web hosting s3 bucket, which we use to host our static webpage
provider:
  name: aws
  stage: prod

resources:
  Resources:
    pwndEc2CodeBucket:
      Type: "AWS::S3::Bucket"
      Properties:
        AccessControl: Private
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
    pwndRawDataBucket:
      Type: "AWS::S3::Bucket"
      Properties:
        AccessControl: Private
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        # S3 Bucket for Static Website Hosting
    staticSiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false

  Outputs:
    PwndCodeBucket:
      Description: The name of the S3 bucket where API Code is kept
      Value: !Ref pwndEc2CodeBucket
    PwndRawDataBucket:
      Description: The name of the S3 bucket where Credentials files can be uploaded to be added to Database
      Value: !Ref pwndRawDataBucket
    StaticSiteBucket:
      Description: The name of the S3 bucket where dashBoard is hosted
      Value: !Ref staticSiteBucket
